-- ============================================================================
-- NÓMINAS (Guatemala) - Esquema Base en Oracle SQL
-- Guía basada en cálculos típicos de planilla (IGSS, ISR), proyecciones, etc.
-- Compatible con Oracle 12c+ (IDENTITY). Nombres prefijados por área.
-- ============================================================================

-- Recomendación: ejecutar en un esquema dedicado (USUARIO) con NLS_DATE_FORMAT='YYYY-MM-DD'.

-- =====================
-- CATÁLOGOS BÁSICOS
-- =====================

CREATE TABLE NOM_DEPARTAMENTO (
  DEP_DEPARTAMENTO_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DEP_CODIGO             VARCHAR2(20)  NOT NULL,
  DEP_NOMBRE             VARCHAR2(120) NOT NULL,
  DEP_ACTIVO             CHAR(1) DEFAULT 'S' CHECK (DEP_ACTIVO IN ('S','N')),
  CONSTRAINT UK_DEP_CODIGO UNIQUE (DEP_CODIGO)
);

CREATE TABLE NOM_PUESTO (
  PUE_PUESTO_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PUE_CODIGO             VARCHAR2(20)  NOT NULL,
  PUE_NOMBRE             VARCHAR2(120) NOT NULL,
  PUE_ACTIVO             CHAR(1) DEFAULT 'S' CHECK (PUE_ACTIVO IN ('S','N')),
  CONSTRAINT UK_PUE_CODIGO UNIQUE (PUE_CODIGO)
);

CREATE TABLE NOM_TIPO_CONTRATO (
  TCO_TIPO_CONTRATO_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TCO_CODIGO             VARCHAR2(20)  NOT NULL,
  TCO_NOMBRE             VARCHAR2(120) NOT NULL,
  TCO_ACTIVO             CHAR(1) DEFAULT 'S' CHECK (TCO_ACTIVO IN ('S','N')),
  CONSTRAINT UK_TCO_CODIGO UNIQUE (TCO_CODIGO)
);

CREATE TABLE NOM_PERIODICIDAD (
  PER_PERIODICIDAD_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PER_CODIGO             VARCHAR2(20) NOT NULL, -- SEMANAL, QUINCENAL, MENSUAL
  PER_NOMBRE             VARCHAR2(60) NOT NULL,
  PER_DIAS_PROMEDIO      NUMBER(5,2) NOT NULL,  -- 7, 15, 30, etc.
  CONSTRAINT UK_PER_CODIGO UNIQUE (PER_CODIGO)
);

CREATE TABLE NOM_BANCO (
  BAN_BANCO_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BAN_CODIGO             VARCHAR2(10) NOT NULL,
  BAN_NOMBRE             VARCHAR2(120) NOT NULL,
  CONSTRAINT UK_BAN_CODIGO UNIQUE (BAN_CODIGO)
);

CREATE TABLE NOM_JORNADA (
  JOR_JORNADA_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  JOR_CODIGO             VARCHAR2(20) NOT NULL, -- DIURNA, NOCTURNA, MIXTA
  JOR_NOMBRE             VARCHAR2(100) NOT NULL,
  JOR_HORAS_DIARIAS      NUMBER(4,2)  DEFAULT 8,
  CONSTRAINT UK_JOR_CODIGO UNIQUE (JOR_CODIGO)
);

-- =====================
-- EMPLEADOS
-- =====================

CREATE TABLE NOM_EMPLEADO (
  EMP_EMPLEADO_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMP_CODIGO_EMP         VARCHAR2(30) NOT NULL,
  EMP_DPI                VARCHAR2(20),
  EMP_NIT                VARCHAR2(20),
  EMP_NOMBRES            VARCHAR2(120) NOT NULL,
  EMP_APELLIDOS          VARCHAR2(120) NOT NULL,
  EMP_FECHA_NAC          DATE,
  EMP_SEXO               CHAR(1) CHECK (EMP_SEXO IN ('M','F')),
  EMP_EMAIL              VARCHAR2(150),
  EMP_TELEFONO           VARCHAR2(30),
  EMP_DIRECCION          VARCHAR2(250),
  EMP_ESTADO_CIVIL       VARCHAR2(20),
  EMP_DEPENDIENTES       NUMBER(2) DEFAULT 0 CHECK (EMP_DEPENDIENTES >= 0),
  EMP_ACTIVO             CHAR(1) DEFAULT 'S' CHECK (EMP_ACTIVO IN ('S','N')),
  CONSTRAINT UK_EMP_CODIGO UNIQUE (EMP_CODIGO_EMP),
  CONSTRAINT UK_EMP_DPI UNIQUE (EMP_DPI),
  CONSTRAINT UK_EMP_NIT UNIQUE (EMP_NIT)
);

CREATE TABLE NOM_EMPLEADO_CONTACTO (
  ECO_CONTACTO_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMP_EMPLEADO_ID        NUMBER NOT NULL,
  ECO_TIPO               VARCHAR2(30) NOT NULL, -- EMERGENCIA, REFERENCIA, etc.
  ECO_NOMBRE             VARCHAR2(120) NOT NULL,
  ECO_PARENTESCO         VARCHAR2(60),
  ECO_TELEFONO           VARCHAR2(30),
  ECO_EMAIL              VARCHAR2(150),
  CONSTRAINT FK_ECO_EMP FOREIGN KEY (EMP_EMPLEADO_ID) REFERENCES NOM_EMPLEADO (EMP_EMPLEADO_ID)
);

CREATE TABLE NOM_EMPLEADO_CUENTA (
  EBC_CUENTA_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMP_EMPLEADO_ID        NUMBER NOT NULL,
  BAN_BANCO_ID           NUMBER,
  EBC_TIPO               VARCHAR2(20) DEFAULT 'AHORRO', -- AHORRO/CORRIENTE
  EBC_NUMERO             VARCHAR2(40),
  EBC_PORCENTAJE_PAGO    NUMBER(5,2) DEFAULT 100 CHECK (EBC_PORCENTAJE_PAGO BETWEEN 0 AND 100),
  CONSTRAINT FK_EBC_EMP FOREIGN KEY (EMP_EMPLEADO_ID) REFERENCES NOM_EMPLEADO (EMP_EMPLEADO_ID),
  CONSTRAINT FK_EBC_BAN FOREIGN KEY (BAN_BANCO_ID) REFERENCES NOM_BANCO (BAN_BANCO_ID)
);

-- =====================
-- CONTRATACIÓN Y SALARIOS
-- =====================

CREATE TABLE NOM_CONTRATO (
  CON_CONTRATO_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMP_EMPLEADO_ID        NUMBER NOT NULL,
  PUE_PUESTO_ID          NUMBER NOT NULL,
  DEP_DEPARTAMENTO_ID    NUMBER NOT NULL,
  TCO_TIPO_CONTRATO_ID   NUMBER NOT NULL,
  PER_PERIODICIDAD_ID    NUMBER NOT NULL,
  JOR_JORNADA_ID         NUMBER,
  CON_FECHA_INICIO       DATE NOT NULL,
  CON_FECHA_FIN          DATE,
  CON_SALARIO_BASE       NUMBER(12,2) NOT NULL,
  CON_FORMA_PAGO         VARCHAR2(20) DEFAULT 'TRANSFERENCIA', -- EFECTIVO, CHEQUE, TRANSFERENCIA
  CON_ESTADO             VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (CON_ESTADO IN ('ACTIVO','SUSPENDIDO','FINALIZADO')),
  CON_SUBSIDIO           NUMBER(12,2) DEFAULT 0,  -- bono decreto, etc.
  CON_OBSERVACIONES      VARCHAR2(4000),
  CONSTRAINT FK_CON_EMP FOREIGN KEY (EMP_EMPLEADO_ID) REFERENCES NOM_EMPLEADO (EMP_EMPLEADO_ID),
  CONSTRAINT FK_CON_PUE FOREIGN KEY (PUE_PUESTO_ID) REFERENCES NOM_PUESTO (PUE_PUESTO_ID),
  CONSTRAINT FK_CON_DEP FOREIGN KEY (DEP_DEPARTAMENTO_ID) REFERENCES NOM_DEPARTAMENTO (DEP_DEPARTAMENTO_ID),
  CONSTRAINT FK_CON_TCO FOREIGN KEY (TCO_TIPO_CONTRATO_ID) REFERENCES NOM_TIPO_CONTRATO (TCO_TIPO_CONTRATO_ID),
  CONSTRAINT FK_CON_PER FOREIGN KEY (PER_PERIODICIDAD_ID) REFERENCES NOM_PERIODICIDAD (PER_PERIODICIDAD_ID),
  CONSTRAINT FK_CON_JOR FOREIGN KEY (JOR_JORNADA_ID) REFERENCES NOM_JORNADA (JOR_JORNADA_ID)
);

CREATE TABLE NOM_SALARIO_HIST (
  SAL_HIST_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  SAL_FECHA_EFECTIVA     DATE NOT NULL,
  SAL_SALARIO_BASE       NUMBER(12,2) NOT NULL,
  SAL_SUBSIDIO           NUMBER(12,2) DEFAULT 0,
  SAL_MOTIVO             VARCHAR2(200),
  CONSTRAINT FK_SAL_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID)
);

-- =====================
-- PARÁMETROS LEGALES (IGSS / ISR Guatemala)
-- =====================

CREATE TABLE NOM_IGSS_PARAM (
  IGS_PARAM_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  IGS_ANIO               NUMBER(4) NOT NULL,
  IGS_TASA_PATRONAL      NUMBER(5,2) NOT NULL,  -- %
  IGS_TASA_LABORAL       NUMBER(5,2) NOT NULL,  -- %
  IGS_TOPE_BASE          NUMBER(12,2),         -- si aplica tope salarial
  CONSTRAINT UK_IGS_ANIO UNIQUE (IGS_ANIO)
);

CREATE TABLE NOM_ISR_TABLA (
  ISR_TABLA_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ISR_ANIO               NUMBER(4) NOT NULL,
  ISR_TRAMO_NUM          NUMBER(2) NOT NULL,
  ISR_DESDE              NUMBER(12,2) NOT NULL,
  ISR_HASTA              NUMBER(12,2),       -- NULL = sin límite
  ISR_TASA               NUMBER(6,4) NOT NULL, -- 0.05 = 5%
  ISR_CUOTA_FIJA         NUMBER(12,2) DEFAULT 0,
  CONSTRAINT UK_ISR_TRAMO UNIQUE (ISR_ANIO, ISR_TRAMO_NUM)
);

-- =====================
-- CONCEPTOS, PERÍODOS Y NÓMINAS
-- =====================

CREATE TABLE NOM_CONCEPTO (
  CNC_CONCEPTO_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CNC_CODIGO             VARCHAR2(20) NOT NULL,
  CNC_NOMBRE             VARCHAR2(120) NOT NULL,
  CNC_TIPO               VARCHAR2(20) NOT NULL CHECK (CNC_TIPO IN ('PERCEPCION','DEDUCCION','APORTE_PATRONAL')),
  CNC_GRAVA_IGSS         CHAR(1) DEFAULT 'S' CHECK (CNC_GRAVA_IGSS IN ('S','N')),
  CNC_GRAVA_ISR          CHAR(1) DEFAULT 'S' CHECK (CNC_GRAVA_ISR IN ('S','N')),
  CNC_ES_HORAS_EXTRA     CHAR(1) DEFAULT 'N' CHECK (CNC_ES_HORAS_EXTRA IN ('S','N')),
  CNC_ES_AUSENCIA        CHAR(1) DEFAULT 'N' CHECK (CNC_ES_AUSENCIA IN ('S','N')),
  CNC_ES_VACACION        CHAR(1) DEFAULT 'N' CHECK (CNC_ES_VACACION IN ('S','N')),
  CNC_FORMULA            VARCHAR2(4000), -- opcional: expresión para cálculo
  CNC_ACTIVO             CHAR(1) DEFAULT 'S' CHECK (CNC_ACTIVO IN ('S','N')),
  CONSTRAINT UK_CNC_CODIGO UNIQUE (CNC_CODIGO)
);

CREATE TABLE NOM_PERIODO_NOMINA (
  PNO_PERIODO_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PER_PERIODICIDAD_ID    NUMBER NOT NULL,
  PNO_ANIO               NUMBER(4) NOT NULL,
  PNO_NUMERO             NUMBER(4) NOT NULL, -- # de periodo dentro del año (semana/quincena/mes)
  PNO_FECHA_INICIO       DATE NOT NULL,
  PNO_FECHA_FIN          DATE NOT NULL,
  PNO_ESTADO             VARCHAR2(20) DEFAULT 'ABIERTO' CHECK (PNO_ESTADO IN ('ABIERTO','CALCULADO','CERRADO','ANULADO')),
  CONSTRAINT UK_PNO_PERIODO UNIQUE (PER_PERIODICIDAD_ID, PNO_ANIO, PNO_NUMERO),
  CONSTRAINT FK_PNO_PER FOREIGN KEY (PER_PERIODICIDAD_ID) REFERENCES NOM_PERIODICIDAD (PER_PERIODICIDAD_ID)
);

CREATE TABLE NOM_NOMINA (
  NOM_NOMINA_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PNO_PERIODO_ID         NUMBER NOT NULL,
  NOM_FECHA_CALCULO      DATE DEFAULT SYSDATE,
  NOM_DESCRIPCION        VARCHAR2(200),
  NOM_ESTADO             VARCHAR2(20) DEFAULT 'GENERADA' CHECK (NOM_ESTADO IN ('GENERADA','APROBADA','PAGADA','ANULADA')),
  CONSTRAINT FK_NOM_PNO FOREIGN KEY (PNO_PERIODO_ID) REFERENCES NOM_PERIODO_NOMINA (PNO_PERIODO_ID)
);

CREATE TABLE NOM_NOMINA_DETALLE (
  NOD_DETALLE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOM_NOMINA_ID          NUMBER NOT NULL,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  CNC_CONCEPTO_ID        NUMBER NOT NULL,
  NOD_CANTIDAD           NUMBER(10,2) DEFAULT 1,
  NOD_MONTO_UNITARIO     NUMBER(12,2) DEFAULT 0,
  NOD_MONTO_TOTAL        NUMBER(12,2) NOT NULL,
  NOD_ES_GRAVADO_IGSS    CHAR(1) DEFAULT 'S' CHECK (NOD_ES_GRAVADO_IGSS IN ('S','N')),
  NOD_ES_GRAVADO_ISR     CHAR(1) DEFAULT 'S' CHECK (NOD_ES_GRAVADO_ISR IN ('S','N')),
  CONSTRAINT FK_NOD_NOM FOREIGN KEY (NOM_NOMINA_ID) REFERENCES NOM_NOMINA (NOM_NOMINA_ID),
  CONSTRAINT FK_NOD_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID),
  CONSTRAINT FK_NOD_CNC FOREIGN KEY (CNC_CONCEPTO_ID) REFERENCES NOM_CONCEPTO (CNC_CONCEPTO_ID)
);

-- =====================
-- MOVIMIENTOS (HEX, AUSENCIAS, VACACIONES, PRÉSTAMOS)
-- =====================

CREATE TABLE NOM_HORAS_EXTRA (
  HEX_HORA_EXTRA_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  HEX_FECHA              DATE NOT NULL,
  HEX_TIPO               VARCHAR2(20) NOT NULL CHECK (HEX_TIPO IN ('SIMPLE','NOCTURNA','DOBLE','FESTIVO')),
  HEX_HORAS              NUMBER(6,2) NOT NULL CHECK (HEX_HORAS >= 0),
  HEX_FACTOR             NUMBER(6,3) DEFAULT 1.5, -- multiplicador
  HEX_AUTORIZADO_POR     VARCHAR2(120),
  HEX_OBSERVACIONES      VARCHAR2(400),
  CONSTRAINT FK_HEX_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID)
);

CREATE TABLE NOM_AUSENCIA (
  AUS_AUSENCIA_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  AUS_FECHA_INICIO       DATE NOT NULL,
  AUS_FECHA_FIN          DATE NOT NULL,
  AUS_TIPO               VARCHAR2(30) NOT NULL, -- ENFERMEDAD, INJUSTIFICADA, PERMISO, etc.
  AUS_REMUNERADA         CHAR(1) DEFAULT 'N' CHECK (AUS_REMUNERADA IN ('S','N')),
  AUS_OBSERVACIONES      VARCHAR2(400),
  CONSTRAINT FK_AUS_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID)
);

CREATE TABLE NOM_VACACION (
  VAC_VACACION_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  VAC_FECHA_INICIO       DATE NOT NULL,
  VAC_FECHA_FIN          DATE NOT NULL,
  VAC_DIAS               NUMBER(5,2) NOT NULL,
  VAC_PAGADAS            CHAR(1) DEFAULT 'S' CHECK (VAC_PAGADAS IN ('S','N')),
  VAC_OBSERVACIONES      VARCHAR2(400),
  CONSTRAINT FK_VAC_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID)
);

CREATE TABLE NOM_PRESTAMO (
  PRE_PRESTAMO_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  PRE_FECHA              DATE NOT NULL,
  PRE_MONTO              NUMBER(12,2) NOT NULL,
  PRE_TASA_ANUAL         NUMBER(7,4) DEFAULT 0,  -- si aplica
  PRE_PLAZO_MESES        NUMBER(4) NOT NULL,
  PRE_ESTADO             VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (PRE_ESTADO IN ('ACTIVO','LIQUIDADO','ANULADO')),
  PRE_OBSERVACIONES      VARCHAR2(400),
  CONSTRAINT FK_PRE_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID)
);

CREATE TABLE NOM_PRESTAMO_CUOTA (
  PRC_CUOTA_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PRE_PRESTAMO_ID        NUMBER NOT NULL,
  PRC_NUMERO             NUMBER(4) NOT NULL,
  PRC_FECHA_PACTADA      DATE NOT NULL,
  PRC_MONTO_CAPITAL      NUMBER(12,2) DEFAULT 0,
  PRC_MONTO_INTERES      NUMBER(12,2) DEFAULT 0,
  PRC_MONTO_TOTAL        NUMBER(12,2) NOT NULL,
  PRC_PAGADA             CHAR(1) DEFAULT 'N' CHECK (PRC_PAGADA IN ('S','N')),
  PRC_FECHA_PAGO         DATE,
  CONSTRAINT UK_PRC_UNQ UNIQUE (PRE_PRESTAMO_ID, PRC_NUMERO),
  CONSTRAINT FK_PRC_PRE FOREIGN KEY (PRE_PRESTAMO_ID) REFERENCES NOM_PRESTAMO (PRE_PRESTAMO_ID)
);

-- =====================
-- BONOS (Aguinaldo, Bono 14, Bono Decreto) y Liquidaciones
-- =====================

CREATE TABLE NOM_BONO (
  BON_BONO_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  BON_TIPO               VARCHAR2(30) NOT NULL CHECK (BON_TIPO IN ('AGUINALDO','BONO14','DECRETO','ESPECIAL')),
  BON_ANIO               NUMBER(4) NOT NULL,
  BON_MONTO_CALCULADO    NUMBER(12,2) NOT NULL,
  BON_MONTO_PAGADO       NUMBER(12,2) DEFAULT 0,
  BON_FECHA_PAGO         DATE,
  BON_OBSERVACIONES      VARCHAR2(400),
  CONSTRAINT UK_BON_UNQ UNIQUE (CON_CONTRATO_ID, BON_TIPO, BON_ANIO),
  CONSTRAINT FK_BON_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID)
);

CREATE TABLE NOM_LIQUIDACION (
  LIQ_LIQ_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CON_CONTRATO_ID        NUMBER NOT NULL,
  LIQ_FECHA              DATE NOT NULL,
  LIQ_MOTIVO             VARCHAR2(60) NOT NULL, -- DESPIDO, RENUNCIA, etc.
  LIQ_VACACIONES         NUMBER(12,2) DEFAULT 0,
  LIQ_INDEMNIZACION      NUMBER(12,2) DEFAULT 0,
  LIQ_BONOS_PENDIENTES   NUMBER(12,2) DEFAULT 0,
  LIQ_OTROS              NUMBER(12,2) DEFAULT 0,
  LIQ_DEDUCCIONES        NUMBER(12,2) DEFAULT 0,
  LIQ_TOTAL              NUMBER(12,2) NOT NULL,
  LIQ_DETALLE            VARCHAR2(4000),
  CONSTRAINT FK_LIQ_CON FOREIGN KEY (CON_CONTRATO_ID) REFERENCES NOM_CONTRATO (CON_CONTRATO_ID)
);

-- =====================
-- AUDITORÍA BÁSICA
-- =====================

CREATE TABLE NOM_AUDIT_LOG (
  AUD_LOG_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AUD_FECHA              DATE DEFAULT SYSDATE,
  AUD_USUARIO            VARCHAR2(120),
  AUD_ACCION             VARCHAR2(30), -- INSERT/UPDATE/DELETE/CALCULO
  AUD_TABLA              VARCHAR2(60),
  AUD_CLAVE              VARCHAR2(120),
  AUD_DETALLE            VARCHAR2(4000)
);