-- =====================
-- 1. CATÁLOGOS BÁSICOS
-- =====================
INSERT INTO NOM_DEPARTAMENTO (DEP_CODIGO, DEP_NOMBRE) VALUES ('DEP-001', 'Recursos Humanos');
INSERT INTO NOM_PUESTO (PUE_CODIGO, PUE_NOMBRE) VALUES ('PUE-001', 'Analista de Nómina');
INSERT INTO NOM_TIPO_CONTRATO (TCO_CODIGO, TCO_NOMBRE) VALUES ('CONT-001', 'Indefinido');
INSERT INTO NOM_PERIODICIDAD (PER_CODIGO, PER_NOMBRE, PER_DIAS_PROMEDIO) VALUES ('MENSUAL', 'Mensual', 30);
INSERT INTO NOM_BANCO (BAN_CODIGO, BAN_NOMBRE) VALUES ('BANRURAL', 'Banco de Desarrollo Rural');
INSERT INTO NOM_JORNADA (JOR_CODIGO, JOR_NOMBRE, JOR_HORAS_DIARIAS) VALUES ('DIURNA', 'Jornada Diurna', 8);

-- =====================
-- 2. EMPLEADOS
-- =====================
INSERT INTO NOM_EMPLEADO (EMP_CODIGO_EMP, EMP_DPI, EMP_NIT, EMP_NOMBRES, EMP_APELLIDOS, EMP_FECHA_NAC, EMP_SEXO)
VALUES ('EMP-001', '1234567890101', '1234567-8', 'Carlos', 'Ramírez', DATE '1990-05-15', 'M');

-- =====================
-- 3. EMPLEADO CONTACTO / CUENTA
-- =====================
INSERT INTO NOM_EMPLEADO_CONTACTO (EMP_EMPLEADO_ID, ECO_TIPO, ECO_NOMBRE, ECO_PARENTESCO, ECO_TELEFONO)
VALUES (1, 'EMERGENCIA', 'María Ramírez', 'Hermana', '5555-5555');

INSERT INTO NOM_EMPLEADO_CUENTA (EMP_EMPLEADO_ID, BAN_BANCO_ID, EBC_TIPO, EBC_NUMERO)
VALUES (1, 1, 'AHORRO', '1234567890');

-- =====================
-- 4. CONTRATOS Y SALARIOS
-- =====================
INSERT INTO NOM_CONTRATO (EMP_EMPLEADO_ID, PUE_PUESTO_ID, DEP_DEPARTAMENTO_ID, TCO_TIPO_CONTRATO_ID, 
                          PER_PERIODICIDAD_ID, JOR_JORNADA_ID, CON_FECHA_INICIO, CON_SALARIO_BASE)
VALUES (1, 1, 1, 1, 1, 1, DATE '2023-01-01', 4500);

INSERT INTO NOM_SALARIO_HIST (CON_CONTRATO_ID, SAL_FECHA_EFECTIVA, SAL_SALARIO_BASE, SAL_MOTIVO)
VALUES (1, DATE '2023-01-01', 4500, 'Inicio de Contrato');

-- =====================
-- 5. PARÁMETROS LEGALES (IGSS / ISR)
-- =====================
INSERT INTO NOM_IGSS_PARAM (IGS_ANIO, IGS_TASA_PATRONAL, IGS_TASA_LABORAL, IGS_TOPE_BASE)
VALUES (2025, 12.67, 4.83, 6500);

INSERT INTO NOM_ISR_TABLA (ISR_ANIO, ISR_TRAMO_NUM, ISR_DESDE, ISR_HASTA, ISR_TASA, ISR_CUOTA_FIJA)
VALUES (2025, 1, 0, 30000, 0.05, 0);

-- =====================
-- 6. CONCEPTOS
-- =====================
INSERT INTO NOM_CONCEPTO (CNC_CODIGO, CNC_NOMBRE, CNC_TIPO, CNC_GRAVA_IGSS, CNC_GRAVA_ISR)
VALUES ('SBASE', 'Salario Base', 'PERCEPCION', 'S', 'S');

-- =====================
-- 7. PERIODO NÓMINA Y NÓMINA
-- =====================
INSERT INTO NOM_PERIODO_NOMINA (PER_PERIODICIDAD_ID, PNO_ANIO, PNO_NUMERO, PNO_FECHA_INICIO, PNO_FECHA_FIN)
VALUES (1, 2025, 8, DATE '2025-08-01', DATE '2025-08-31');

INSERT INTO NOM_NOMINA (PNO_PERIODO_ID, NOM_DESCRIPCION)
VALUES (1, 'Nómina Agosto 2025');

-- =====================
-- 8. DETALLE DE NÓMINA
-- =====================
INSERT INTO NOM_NOMINA_DETALLE (NOM_NOMINA_ID, CON_CONTRATO_ID, CNC_CONCEPTO_ID, 
                                NOD_CANTIDAD, NOD_MONTO_UNITARIO, NOD_MONTO_TOTAL)
VALUES (1, 1, 1, 1, 4500, 4500);

-- =====================
-- 9. MOVIMIENTOS: HORAS EXTRA, AUSENCIAS, VACACIONES, PRÉSTAMOS
-- =====================
INSERT INTO NOM_HORAS_EXTRA (CON_CONTRATO_ID, HEX_FECHA, HEX_TIPO, HEX_HORAS)
VALUES (1, DATE '2025-08-15', 'SIMPLE', 2);

INSERT INTO NOM_AUSENCIA (CON_CONTRATO_ID, AUS_FECHA_INICIO, AUS_FECHA_FIN, AUS_TIPO)
VALUES (1, DATE '2025-08-10', DATE '2025-08-11', 'ENFERMEDAD');

INSERT INTO NOM_VACACION (CON_CONTRATO_ID, VAC_FECHA_INICIO, VAC_FECHA_FIN, VAC_DIAS)
VALUES (1, DATE '2025-07-01', DATE '2025-07-07', 5);

INSERT INTO NOM_PRESTAMO (CON_CONTRATO_ID, PRE_FECHA, PRE_MONTO, PRE_PLAZO_MESES)
VALUES (1, DATE '2025-07-01', 1200, 12);

INSERT INTO NOM_PRESTAMO_CUOTA (PRE_PRESTAMO_ID, PRC_NUMERO, PRC_FECHA_PACTADA, PRC_MONTO_TOTAL)
VALUES (1, 1, DATE '2025-08-30', 100);

-- =====================
-- 10. BONOS Y LIQUIDACIONES
-- =====================
INSERT INTO NOM_BONO (CON_CONTRATO_ID, BON_TIPO, BON_ANIO, BON_MONTO_CALCULADO)
VALUES (1, 'AGUINALDO', 2025, 2000);

INSERT INTO NOM_LIQUIDACION (CON_CONTRATO_ID, LIQ_FECHA, LIQ_MOTIVO, LIQ_TOTAL)
VALUES (1, DATE '2025-12-31', 'RENUNCIA', 5000);

-- =====================
-- 11. AUDITORÍA (ejemplo)
-- =====================
INSERT INTO NOM_AUDIT_LOG (AUD_USUARIO, AUD_ACCION, AUD_TABLA, AUD_CLAVE, AUD_DETALLE)
VALUES ('admin', 'INSERT', 'NOM_EMPLEADO', '1', 'Empleado insertado manualmente');

--COMMIT;
